import { formatValue } from "@/utils/constants/format-values";
import {
  AlertCircle,
  Calculator,
  DollarSign,
  GitCompare,
  Package,
  Percent,
  ShoppingCart,
  TrendingUp,
  Users,
  Warehouse,
} from "lucide-react";

// Métricas para cada tipo de reporte con iconos mejorados
export const BENTO_METRICS_CONFIG: Record<string, any[]> = {
  ventas: [
    {
      title: "Ventas",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: DollarSign,
      description: "Total en ventas",
    },
    {
      title: "Costos",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: Calculator,
      description: "Total de costos",
    },
    {
      title: "Margen",
      raw: 0,
      display: formatValue(0, "percentage"),
      type: "percent",
      icon: Percent,
      description: "Margen de utilidad",
    },
    {
      title: "Utilidad",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: TrendingUp,
      description: "Utilidad neta",
    },
    {
      title: "Artículos",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "Artículos vendidos",
    },

    {
      title: "Tikets",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "tikets vendidos",
    },
    {
      title: "Promedio",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "promedio venta por tiket",
    },
  ],
  compras: [
    {
      title: "Costo Total",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: Calculator,
      description: "Total de compras",
    },
    {
      title: "Artículos",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "Artículos comprados",
    },
    {
      title: "Proveedores",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Users,
      description: "Proveedores distintos",
    },
  ],
  mermas: [
    {
      title: "Costo Merma",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: AlertCircle,
      description: "Costo por mermas",
    },
    {
      title: "Artículos",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "Artículos con merma",
    },
  ],
  inventario: [
    {
      title: "Costo Total",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: Warehouse,
      description: "Valor del inventario",
    },
    {
      title: "Artículos",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "Artículos en inventario",
    },
  ],
  comparacion: [
    {
      title: "Ventas",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: DollarSign,
      description: "Total de ventas",
    },
    {
      title: "Compras",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: ShoppingCart,
      description: "Total de compras",
    },
    {
      title: "Diferencia",
      raw: 0,
      display: formatValue(0, "currency"),
      type: "currency",
      icon: GitCompare,
      description: "Diferencia venta-compra",
    },
    {
      title: "Margen",
      raw: 0,
      display: formatValue(0, "percentage"),
      type: "percent",
      icon: Percent,
      description: "Margen comparativo",
    },
    {
      title: "Artículos",
      raw: 0,
      display: formatValue(0, "number"),
      type: "number",
      icon: Package,
      description: "Artículos comparados",
    },
  ],
};
